"""Initial migration

Revision ID: f15072677c08
Revises: 
Create Date: 2026-07-06 13:56:33.224155

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f15072677c08'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.String(length=255), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_audit_log_user_id_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('notification',
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_notification_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index(op.f('ix_notification_id'), 'notification', ['id'], unique=False)
    op.create_index(op.f('ix_notification_user_id'), 'notification', ['user_id'], unique=False)
    op.create_table('workspace',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_workspace_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace'))
    )
    op.create_index(op.f('ix_workspace_id'), 'workspace', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_owner_id'), 'workspace', ['owner_id'], unique=False)
    op.create_table('meeting',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='meetingstatus'), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], name=op.f('fk_meeting_workspace_id_workspace')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting'))
    )
    op.create_index(op.f('ix_meeting_id'), 'meeting', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_status'), 'meeting', ['status'], unique=False)
    op.create_index(op.f('ix_meeting_workspace_id'), 'meeting', ['workspace_id'], unique=False)
    op.create_table('action_item',
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('assignee', sa.String(length=255), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('TODO', 'IN_PROGRESS', 'DONE', name='actionitemstatus'), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_action_item_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_item'))
    )
    op.create_index(op.f('ix_action_item_id'), 'action_item', ['id'], unique=False)
    op.create_index(op.f('ix_action_item_meeting_id'), 'action_item', ['meeting_id'], unique=False)
    op.create_table('chat_conversation',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_chat_conversation_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_conversation'))
    )
    op.create_index(op.f('ix_chat_conversation_id'), 'chat_conversation', ['id'], unique=False)
    op.create_index(op.f('ix_chat_conversation_meeting_id'), 'chat_conversation', ['meeting_id'], unique=False)
    op.create_table('decision',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_decision_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision'))
    )
    op.create_index(op.f('ix_decision_id'), 'decision', ['id'], unique=False)
    op.create_index(op.f('ix_decision_meeting_id'), 'decision', ['meeting_id'], unique=False)
    op.create_table('embedding',
    sa.Column('vector_id', sa.String(length=255), nullable=False),
    sa.Column('content_ref', sa.String(length=500), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_embedding_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_embedding'))
    )
    op.create_index(op.f('ix_embedding_id'), 'embedding', ['id'], unique=False)
    op.create_index(op.f('ix_embedding_meeting_id'), 'embedding', ['meeting_id'], unique=False)
    op.create_table('meeting_file',
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_meeting_file_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meeting_file'))
    )
    op.create_index(op.f('ix_meeting_file_id'), 'meeting_file', ['id'], unique=False)
    op.create_index(op.f('ix_meeting_file_meeting_id'), 'meeting_file', ['meeting_id'], unique=False)
    op.create_table('report',
    sa.Column('report_url', sa.String(length=500), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_report_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report'))
    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    op.create_index(op.f('ix_report_meeting_id'), 'report', ['meeting_id'], unique=False)
    op.create_table('sentiment_analysis',
    sa.Column('sentiment_score', sa.Float(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_sentiment_analysis_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sentiment_analysis'))
    )
    op.create_index(op.f('ix_sentiment_analysis_id'), 'sentiment_analysis', ['id'], unique=False)
    op.create_index(op.f('ix_sentiment_analysis_meeting_id'), 'sentiment_analysis', ['meeting_id'], unique=False)
    op.create_table('speaker',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('voice_signature', sa.Text(), nullable=True),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_speaker_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_speaker'))
    )
    op.create_index(op.f('ix_speaker_id'), 'speaker', ['id'], unique=False)
    op.create_index(op.f('ix_speaker_meeting_id'), 'speaker', ['meeting_id'], unique=False)
    op.create_table('summary',
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_summary_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_summary'))
    )
    op.create_index(op.f('ix_summary_id'), 'summary', ['id'], unique=False)
    op.create_index(op.f('ix_summary_meeting_id'), 'summary', ['meeting_id'], unique=True)
    op.create_table('transcript',
    sa.Column('full_text', sa.Text(), nullable=True),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_transcript_meeting_id_meeting'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript'))
    )
    op.create_index(op.f('ix_transcript_id'), 'transcript', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_meeting_id'), 'transcript', ['meeting_id'], unique=True)
    op.create_table('chat_message',
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('conversation_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversation.id'], name=op.f('fk_chat_message_conversation_id_chat_conversation'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_message'))
    )
    op.create_index(op.f('ix_chat_message_conversation_id'), 'chat_message', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_message_id'), 'chat_message', ['id'], unique=False)
    op.create_table('transcript_segment',
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('transcript_id', sa.Uuid(), nullable=False),
    sa.Column('speaker_id', sa.Uuid(), nullable=True),
    sa.Column('meeting_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meeting.id'], name=op.f('fk_transcript_segment_meeting_id_meeting'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['speaker_id'], ['speaker.id'], name=op.f('fk_transcript_segment_speaker_id_speaker'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['transcript_id'], ['transcript.id'], name=op.f('fk_transcript_segment_transcript_id_transcript'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transcript_segment'))
    )
    op.create_index(op.f('ix_transcript_segment_id'), 'transcript_segment', ['id'], unique=False)
    op.create_index(op.f('ix_transcript_segment_meeting_id'), 'transcript_segment', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_transcript_segment_speaker_id'), 'transcript_segment', ['speaker_id'], unique=False)
    op.create_index(op.f('ix_transcript_segment_transcript_id'), 'transcript_segment', ['transcript_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transcript_segment_transcript_id'), table_name='transcript_segment')
    op.drop_index(op.f('ix_transcript_segment_speaker_id'), table_name='transcript_segment')
    op.drop_index(op.f('ix_transcript_segment_meeting_id'), table_name='transcript_segment')
    op.drop_index(op.f('ix_transcript_segment_id'), table_name='transcript_segment')
    op.drop_table('transcript_segment')
    op.drop_index(op.f('ix_chat_message_id'), table_name='chat_message')
    op.drop_index(op.f('ix_chat_message_conversation_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_transcript_meeting_id'), table_name='transcript')
    op.drop_index(op.f('ix_transcript_id'), table_name='transcript')
    op.drop_table('transcript')
    op.drop_index(op.f('ix_summary_meeting_id'), table_name='summary')
    op.drop_index(op.f('ix_summary_id'), table_name='summary')
    op.drop_table('summary')
    op.drop_index(op.f('ix_speaker_meeting_id'), table_name='speaker')
    op.drop_index(op.f('ix_speaker_id'), table_name='speaker')
    op.drop_table('speaker')
    op.drop_index(op.f('ix_sentiment_analysis_meeting_id'), table_name='sentiment_analysis')
    op.drop_index(op.f('ix_sentiment_analysis_id'), table_name='sentiment_analysis')
    op.drop_table('sentiment_analysis')
    op.drop_index(op.f('ix_report_meeting_id'), table_name='report')
    op.drop_index(op.f('ix_report_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_meeting_file_meeting_id'), table_name='meeting_file')
    op.drop_index(op.f('ix_meeting_file_id'), table_name='meeting_file')
    op.drop_table('meeting_file')
    op.drop_index(op.f('ix_embedding_meeting_id'), table_name='embedding')
    op.drop_index(op.f('ix_embedding_id'), table_name='embedding')
    op.drop_table('embedding')
    op.drop_index(op.f('ix_decision_meeting_id'), table_name='decision')
    op.drop_index(op.f('ix_decision_id'), table_name='decision')
    op.drop_table('decision')
    op.drop_index(op.f('ix_chat_conversation_meeting_id'), table_name='chat_conversation')
    op.drop_index(op.f('ix_chat_conversation_id'), table_name='chat_conversation')
    op.drop_table('chat_conversation')
    op.drop_index(op.f('ix_action_item_meeting_id'), table_name='action_item')
    op.drop_index(op.f('ix_action_item_id'), table_name='action_item')
    op.drop_table('action_item')
    op.drop_index(op.f('ix_meeting_workspace_id'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_status'), table_name='meeting')
    op.drop_index(op.f('ix_meeting_id'), table_name='meeting')
    op.drop_table('meeting')
    op.drop_index(op.f('ix_workspace_owner_id'), table_name='workspace')
    op.drop_index(op.f('ix_workspace_id'), table_name='workspace')
    op.drop_table('workspace')
    op.drop_index(op.f('ix_notification_user_id'), table_name='notification')
    op.drop_index(op.f('ix_notification_id'), table_name='notification')
    op.drop_table('notification')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
